# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-03 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Belong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=-1)),
                ('group_id', models.IntegerField(default=-1)),
            ],
        ),
    ]
