# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peoplecomment',
            name='people',
        ),
        migrations.AddField(
            model_name='peoplecomment',
            name='commentid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peoplecomment',
            name='date',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peoplecomment',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peoplecomment',
            name='star',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peoplecomment',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peoplecomment',
            name='userid',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peoplecomment',
            name='fileid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='peoplefollowpeople',
            name='followee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peoplefollowpeople',
            name='follower',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peoplestarfile',
            name='fileid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='peoplestarfile',
            name='people',
            field=models.IntegerField(default=0),
        ),
    ]
