# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_auto_20171110_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplecomment',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
