# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NoticeRemainder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='date',
        ),
        migrations.AddField(
            model_name='notice',
            name='time',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
