# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NoticeRemainder', '0002_auto_20171103_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='time',
        ),
    ]
