# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-20 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileToTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField(default=0)),
                ('tag_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StFile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StTag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='FileToGroup',
        ),
    ]
