# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-21 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20171020_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='sttag',
            name='isGroup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stfile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sttag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
