# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-07 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_remove_stfile_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stfile',
            old_name='owner',
            new_name='ownerID',
        ),
    ]
